### ISSUE TITLE
stare_intersects returns wrong dataframe indices

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREPandas#118]
stare_intersects will always return sequential indices starting from zero. This breaks when a dataframe has been subset by other means and thus does not have sequential indices

**Comment by michaelleerilee** [comment]
How about re-indexing the intermediate result as a workaround?

**Comment by NiklasPhabian** [comment]
Yes exactly that is the workaround. One has to reindex after subsetting. Just annoying when you forget and get an unsuspected error.

**Comment by NiklasPhabian** [comment]
duplicate of #86
