### ISSUE TITLE
Example: ellipses.ipynb

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#138]
This seems like magic. Where are the semi-major and minor axis parameters? Or are these IFOV footprints from MODIS?

**Comment by NiklasPhabian** [comment]
You are referring to 

- https://starepandas.readthedocs.io/en/latest/examples/notebooks/ellipses.html
- https://github.com/SpatioTemporal/STAREPandas/blob/master/examples/ellipses.ipynb

the notebook needs more documentation so I will leave this ticket open until I edit the notebook accordingly

Those are approximations for the MODIS IFOVs. The length of the semi-major axis and semi-minor axis are calculated from the scan angle; their orientation from their azimuth. The lengths are fitted to parameters in the MODIS geolocation ATBD:

https://github.com/NiklasPhabian/dissertation/blob/main/mds/C3_Spires.md#ifov-approximation-labelsec_ifov

**Comment by NiklasPhabian** [comment]
https://github.com/SpatioTemporal/STAREPandas/blob/master/starepandas/io/granules/modis.py#L456
