### ISSUE TITLE
STARE column as index

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREPandas#24]
Would it ever make sense to use the STARE column as the dataframe index?
Pandas indices do __not__ have to be unique and can be any numpy data type.

In some case it may be useful to have the SID as the index rather than as an attribute.
The issue here is that all functions that operate on the SIDs expect the SIDs to be in the ```DataFrame._stare_column_name ```attribute, so we would need to catch this somehow. Maybe by adding a bool object attribute ```DataFrame._stare_is_index```?

**Comment by michaelleerilee** [comment]
DB
