### ISSUE TITLE
How efficient is STAREPandas visualization of STARE? Can it be factored out?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#3]
Using Matplotlib's Triangulation to visualize STARE spatial values & associated data seems slow. Is STAREPandas approach faster? If it is, can we come up with some protocols, pystare functions, or Jupyter notebooks describing how to efficiently plot STARE-indexed data?

**Comment by NiklasPhabian** [comment]
do you have a showcase notebook that displays how you usually plot and the shortcomings.

**Comment by michaelleerilee** [comment]
At the end of the following notebook I have an example using the 5km data. It looks like the pandas approach is not as fast as directly using matplotlib.tri. I don't know enough about the internals or possible caching... 
https://github.com/SpatioTemporal/STARE-Cookbooks/blob/master/contrib/jupyter/9y-SidecarFile-Introduction.ipynb

    On Friday, September 11, 2020, 03:43:24 PM EDT, Niklas Griessbaum <notifications@github.com> wrote:  
 
 


do you have a showcase notebook that displays how you usually plot and the shortcomings.
