### ISSUE TITLE
Proposed granule_factory

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#35]
I'm looking at opening up `granule_factory` so that end-users can add a regex/granule pair to STAREPandas.

Please examine the following.

https://github.com/SpatioTemporal/STAREPandas/blob/de35e893cd0cbb64d8206d38f01b1d9b276aaefd/starepandas/io/granules/__init__.py#L62-L78

This currently uses a dict, but if we get lots of entries, maybe we can switch to a sorted_dict.

Now we need a way to access `granule_factory_library` and the base class `granule`.

**Comment by michaelleerilee** [comment]
Check out this example.

https://github.com/SpatioTemporal/STAREPandas/blob/granular_democracy/examples/XX-UserSpecifiedGranuleLoader.ipynb

**Comment by michaelleerilee** [comment]
Now I need to figure out how to write a `granule` that will open up a geolocation file.

**Comment by michaelleerilee** [comment]
Looks like I can create two granule classes, one for the data and another for the geolocations. Then load each and add the needed columns to the starepandas dataframe.

Is that the right way, @NiklasPhabian?

**Comment by michaelleerilee** [comment]
Note: MOD14 uses MOD03.

**Comment by NiklasPhabian** [comment]
> Looks like I can create two granule classes, one for the data and another for the geolocations. Then load each and add the needed columns to the starepandas dataframe.

Yes. Correct. Since the datasets in the granule and the geolocation granule are of the same shape and are flattened in the same order, you can simply do an index table join

```python3
joined = geolocation.join(granule)
```

This is how I did it for VNP02DNB and VNP03DNB. 
https://github.com/SpatioTemporal/STAREPandas/blob/granular_democracy/examples/VNP02DNB.ipynb

Sidenote: We also have the ```starepandas.io.granules.guess_companion_path(file_path, prefix, folder)``` function that tries to guess the path of a companion subject to the granule path

**Comment by NiklasPhabian** [comment]
> Check out this example.
> 
> https://github.com/SpatioTemporal/STAREPandas/blob/granular_democracy/examples/XX-UserSpecifiedGranuleLoader.ipynb

I see how you used this elegant approach at the end of the notebook. We should prettify this notebook (comments, structure) and link it into the documentation of [read_granule](https://github.com/SpatioTemporal/STAREPandas/blob/a918c065b911e713051ac9828ecffd74e382fc04/starepandas/io/granules/__init__.py#L103) and/or add such an example straight to the docstring

**Comment by michaelleerilee** [comment]
Looks like I should be calling `granule.to_df()` at some point.

**Comment by michaelleerilee** [comment]
Should we explicitly declare class parentage?

I.e.
```
class Granule(object):
...
```

**Comment by NiklasPhabian** [comment]
No. Not necessary in python3

**Comment by michaelleerilee** [comment]
Is that the currently recommended style?

**Comment by NiklasPhabian** [comment]
Currently not necessary to inherit from object, yes.
It's called 'new-style classes'classes'
https://portingguide.readthedocs.io/en/latest/classes.html

**Comment by michaelleerilee** [comment]
Just wondering because "No CamelCase" is also not necessary.

**Comment by NiklasPhabian** [comment]
@michaelleerilee how are we feeling about the granule_democracy?
Are you satisfied with it this far? If so, we should add some tests and make a PR.
