### ISSUE TITLE
AttributeError: module 'pystare' has no attribute 'from_latlon2D'

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#36]
Seems a dep is out of sync.

AttributeError: module 'pystare' has no attribute 'from_latlon2D'

**Comment by michaelleerilee** [comment]
Are we using 'level' or 'resolution'?

**Comment by NiklasPhabian** [comment]
> Seems a dep is out of sync.
> 
> AttributeError: module 'pystare' has no attribute 'from_latlon2D'

correct. [pystare 0.8.0 renamed ```from_latlon2D()``` to pep-conform ```from_latlon_2d()```](https://github.com/SpatioTemporal/pystare/blob/dd1a6d67b5acb7a304113ab6b9262b9b4de06cfc/pystare/spatial.py#L54)

I knew that something was fishy. We have to require ```pystare>=0.8.0```. This is specified correctly in the ```requirements.txt```. However, we are not using this one during install anymore. I am somewhat confused what ```requirements.txt``` is actually for nowadays and if it should be included in a project at all. I guess github dependabots uses it?

Where one *actually* specifies the dependencies in a modern project seems to be in ```setup.cfg```. I'd vote to remove requirements.txt to avoid over-specifying dependencies and thus run into such an issue again.
> Are we using 'level' or 'resolution'?

I was wondering about the [same thing](https://github.com/SpatioTemporal/STAREPandas/issues/8). I renamed all keywords in pystare to level; no more resolution.

**Comment by NiklasPhabian** [comment]
fixed here: https://github.com/SpatioTemporal/STAREPandas/commit/489da9d615b6db08ffdcefa04dfdfa2185395e77

**Comment by NiklasPhabian** [comment]
> I was wondering about the [same thing](https://github.com/SpatioTemporal/STAREPandas/issues/8). I renamed all keywords in pystare to level; no more resolution.

I need to verify if I have been thorough in STAREPandas as well

**Comment by michaelleerilee** [comment]
Kuo recommended we standardize on resolution as that is the scientifically relevant idea. So I went through and changed most (but not all [sigh]) of the arguments in STARE.h to resolution or resolution_level.

Well, at least the python side is mostly consistent.

Note: level vs. resolution is low priority at the moment.
