### ISSUE TITLE
granule.add_stare() can almost trivially be parallelized

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#39]
Dask would be easy in the method itself, though we should also ask the STARE developers to parallelize/multithread the library function.

**Comment by NiklasPhabian** [comment]
Yes, let's ask them. Pragmatically, it does not seem to matter for
starepandas. Note that e.g. STAREDataFrame.make_stare() has the option to
use dask.

**Comment by NiklasPhabian** [comment]
function is now called make_sids()
