### ISSUE TITLE
Is there a connection between Xarray and STAREPandas?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#40]
Columns seem to be numpy--or something else?

**Comment by NiklasPhabian** [comment]
Good question. It almost seems to me that xarrays are orthogonal to data
frames. Data frames are inherently 1 or 2 dimensional. Each frame is a 2d
numpy array. Pandas keeps track of names and metadata (just like xarray) on
top of that. It is somewhat odd though. The notion of pivoting a table
feels very similar to working with a n-dimensional array. Data frames
therefore seem like a special case of an xarray. But historically, pandas
came first.
