### ISSUE TITLE
read granules with rioxarray

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREPandas#77]
We might have an opportunity to avoid writing our own granule drivers.
At least HDFEOS seems to be handled by gdal. Which in turn is exposed through rasterio.
might be as simple as:

```
modis = rioxarray.open_rasterio(granulke_name, variable=bands)
```

https://corteva.github.io/rioxarray/stable/rioxarray.html

**Comment by michaelleerilee** [comment]
Does this work for L2 that has geolocation overlaps?

**Comment by NiklasPhabian** [comment]
I actually only tested for L3 data. GDAL reads this with the driver: "HDF4_EOS:EOS_GRID"
But there also seems to be fore L1/L2: "HDF4_EOS:EOS_SWATH". 

None of this is well documented. But abstracted by rasterio, which in turn is abstracted by rioxarray. This all just might be a catch-all easy way of reading hdfeos/4/5 and netcdf reader. I will experiment when I add a support for new product

**Comment by NiklasPhabian** [comment]
screw this. Rasterio and rioxarray are terribly idiosyncratic for geotiff.
