### ISSUE TITLE
intersects example/ STAREDataFrame.set_pixels inplace doesn't work.

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#87]
![image](https://user-images.githubusercontent.com/6934724/166678667-7e4a460c-647c-481b-958f-e52fb5f9116c.png)

**Comment by michaelleerilee** [comment]
This seems to work.

iceland.set_trixels(iceland.make_trixels(),inplace=True)

**Comment by NiklasPhabian** [comment]
yes. This is the intended usage!
