### ISSUE TITLE
intersects example no longer plots points

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#88]
https://github.com/SpatioTemporal/STAREPandas/blob/master/examples/intersects.ipynb

**Comment by michaelleerilee** [comment]
Here's what's on github.

![image](https://user-images.githubusercontent.com/6934724/166682301-8daa5cc6-8668-4e8d-a548-da5f3195eebd.png)

Here's what I'm getting.

![image](https://user-images.githubusercontent.com/6934724/166682549-15f2d61c-3b3a-43a5-8272-772e8b196705.png)

**Comment by michaelleerilee** [comment]
How would I get points back?

**Comment by NiklasPhabian** [comment]
the plot command has a kwarg `trixels`. If you set this to false, the original geometry should be ploted.

**Comment by NiklasPhabian** [comment]
https://starepandas.readthedocs.io/en/latest/docs/reference/api/starepandas.STAREDataFrame.plot.html
