### ISSUE TITLE
How do I load a file into starepandas?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#90]
I follow the example [intersects](https://github.com/SpatioTemporal/STAREPandas/blob/master/examples/intersects.ipynb) to get a path to a file, but it tells me the file isn't there.

![image](https://user-images.githubusercontent.com/6934724/166692144-113205f6-d208-45d5-b32f-5131f82bb57a.png)

**Comment by NiklasPhabian** [comment]
we would have to add support for this product and then do something like
```python
sdf = starepandas.read_granule(file_path)
```
