### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#92]
Made progress loading. Now how to visualize?

![image](https://user-images.githubusercontent.com/6934724/166726991-f43db1bd-8ca9-45d0-a00e-ae2bc07c4560.png)

**Comment by NiklasPhabian** [comment]
you'd have to create the trixels with 

```python
trixels = composite.make_trixels()
composite.set_trixels(trixels, inplace=True
composite.plot()
```
