### ISSUE TITLE
How do I store a dataframe for future use?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#94]
![image](https://user-images.githubusercontent.com/6934724/167305015-8e973489-698c-4ddd-9fdc-7b7be729258f.png)

**Comment by NiklasPhabian** [comment]
we will need to conform to a schema to use HDF. You are almost certainly safer to store to pickle for now
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html

**Comment by NiklasPhabian** [comment]
Well. OK. To write to HDF5, we'd probably either find a way of serializing the geometry column, or drop it. The latter:

```python
roi.drop(columns='geometry').to_hdf('roi.h5', key='roi')
```

**Comment by NiklasPhabian** [comment]
For now: pickle or geopackages. We have not come up with an hdf schema yet.
I would think all it takes would be converting some of the data types. Is
this a priority for you?
