### ISSUE TITLE
Might wish to consider an engine keyword like xarray for IO.

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#98]

**Comment by NiklasPhabian** [comment]
are you thinking through [```xarray.open_rasterio()```](https://docs.xarray.dev/en/stable/generated/xarray.open_rasterio.html)?
(Which seems to be deprecated in favor of rioxarray). 

What kind of benefits would we expect to change the engine? Reading with rioxarray would allow lazy loading I guess; but performance-wise, rioxarray and open_rasterio() seem to abstract rasterio which presumably loads through GDAL, which presumably loads through HDF4/5 netCDF libraries. I would not expect a speedup here.

**Comment by NiklasPhabian** [comment]
on the other hand, we might consider swapping out netcdf4, h5py and pyhdf4 with just rioxarray to use a common interface for all three. We'd need to be careful to ship a rasterio version that supports all 3 file formats though.
